### ISSUE TITLE
Upgrade Gatsby to 5.12.0+: Migrate serverless functions to V2 API

### ISSUE THREAD

**Issue by breedy231** [breedy231/site#33]
## Current Status

**Gatsby version**: Locked at 5.11.0  
**Blocker**: Gatsby 5.12.0+ requires migration of all serverless functions to modern Netlify Functions V2 API

## Problem

Starting with Gatsby 5.12.0, Gatsby automatically:
1. Installs `gatsby-adapter-netlify` during Netlify builds (no opt-out)
2. Removes `gatsby-plugin-netlify` 
3. **Requires ALL functions to use modern V2 API format** (Request/Response objects)

This is a breaking change that causes 502 errors with "res.status is not a function" if functions use the old Express-style format.

**Reference**: https://github.com/gatsbyjs/gatsby/issues/38542

## Current Directory Structure

```
src/api/           - Source functions (Express-style: req, res) ❌ OLD FORMAT
netlify/functions/ - Deployed functions (Modern V2: Request/Response) ✅ NEW FORMAT
```

**CRITICAL**: These directories currently use DIFFERENT API formats!
- `netlify/functions/` uses modern V2 format (committed to git, works with Gatsby 5.11.0)
- `src/api/` uses legacy Express-style format
- The prebuild script copies from `src/api/` to `netlify/functions/`, which would break things

### Phase 1: Migrate src/api functions to V2 format

Update all functions in `src/api/`:
- [ ] `src/api/history.js`
- [ ] `src/api/goodreads.js`
- [ ] `src/api/lastfm.js`
- [ ] `src/api/trakt-token.js`
- [ ] `src/api/refresh-token.js` (if exists)

**API Changes Required**:
```javascript
// OLD (Express-style)
export default async function handler(req, res) {
  if (req.method !== "GET") {
    return res.status(405).json({ message: "Method not allowed" })
  }
  
  const token = req.headers.authorization
  const { code } = req.body
  
  return res.status(200).json(data)
}

// NEW (Modern V2)
export default async function handler(req) {
  if (req.method !== "GET") {
    return new Response(JSON.stringify({ message: "Method not allowed" }), {
      status: 405,
      headers: { "Content-Type": "application/json" }
    })
  }
  
  const token = req.headers.get("authorization")
  const { code } = await req.json()
  
  return new Response(JSON.stringify(data), {
    status: 200,
    headers: { "Content-Type": "application/json" }
  })
}
```

### Phase 2: Testing

- [ ] Test each migrated function locally with `gatsby develop`
- [ ] Verify prebuild script correctly copies to `netlify/functions/`
- [ ] Deploy to a test environment
- [ ] Test all API endpoints on staging
- [ ] Verify token refresh flow works
- [ ] Test OAuth flows (Trakt authentication)

### Phase 3: Upgrade Gatsby

- [ ] Update `package.json`: `gatsby@^5.12.0` → `gatsby@^5.13.0` (or latest)
- [ ] Update `gatsby-cli` to matching version
- [ ] Test build locally
- [ ] Deploy to staging
- [ ] Monitor Netlify function logs for errors
- [ ] Verify adapter is working correctly

### Phase 4: Cleanup

- [ ] Remove V2 format from `netlify/functions/` (since prebuild will handle it)
- [ ] Update CLAUDE.md to reflect single source of truth
- [ ] Remove Gatsby version lock warning from docs

## Benefits of Upgrading

- **Security**: Get latest Gatsby security patches (5.11.0 → 5.13.0+)
- **Features**: Access new Gatsby features and improvements
- **Maintenance**: Stay on supported version track
- **Performance**: Benefit from adapter optimizations

## References

- [Gatsby Issue #38542](https://github.com/gatsbyjs/gatsby/issues/38542) - Adapter breaking changes
- [Netlify Functions V2 Migration Guide](https://developers.netlify.com/guides/migrating-to-the-modern-netlify-functions/)
- [Gatsby Adapter Documentation](https://www.gatsbyjs.com/docs/how-to/previews-deploys-hosting/adapters/)

## Estimated Effort

**Time**: 2-4 hours  
**Complexity**: Medium  
**Risk**: Medium (requires careful testing of all API endpoints)

---

**Related PR**: #32 (Dependabot security fixes - downgraded Gatsby to avoid this issue)
